services:
  php:
    build: .
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      APP_ENV: dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  dbdata: {}